In recent years, there has a tendency in the software engineering community towards cloud computing. Cloud platforms
are gaining mainstream adoption as the preferred delivery and
operating model for modern applications by several companies
like Amazon, Microsoft and IBM [1].

The changing infrastructural circumstances lead to architectural styles that take advantage of the opportunities given
by cloud infrastructures. An architectural style that has become more relevant in the last years and that allows taking
advantage of the benefits obtained with cloud computing is
the Microservices Architecture (MSA) [2].


Monolithic Architecture (MA), instead, was the traditional
approach to software development, used in the past by large
companies like Amazon and Ebay. In MA, the functions are
encapsulated into a single application. Monolith application, if
not complicated, have their own strength, for instance, easiness of development, testing and deployment. However, when the
application tends to become more complicated, the monolith
structure grows in size, becoming a large, hard to manage and
scale piece of software [6]. 


of development, testing and deployment. However, when the
application tends to become more complicated, the monolith
structure grows in size, becoming a large, hard to manage and
scale piece of software [6].


of development, testing and deployment. However, when the
application tends to become more complicated, the monolith
structure grows in size, becoming a large, hard to manage and
scale piece of software [6].