apiVersion: v1
kind: PersistentVolume
metadata:
  name: text-to-voice-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/text-to-voice" # Ensure this path is correct on your node
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: text-to-voice-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
