apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-cloud-config-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-cloud-config-server
  template:
    metadata:
      labels:
        app: spring-cloud-config-server
    spec:
      containers:
        - name: spring-cloud-config-server
          image: trexhepaj/mmv-spring-cloud-config-server:0.0.1-SNAPSHOT
          resources:
            limits:
              memory: "700Mi"
          ports:
            - containerPort: 8888
          env:
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              value: http://naming-server:8761/eureka/
---
apiVersion: v1
kind: Service
metadata:
  name: spring-cloud-config-server
spec:
  ports:
    - port: 8888
      targetPort: 8888
  selector:
    app: spring-cloud-config-server
