apiVersion: v1
kind: Service
metadata:
  name: spring-cloud-config-server
spec:
  type: LoadBalancer
  selector:
    app: spring-cloud-config-server
  ports:
    - protocol: TCP
      port: 8888
      targetPort: 8888
