apiVersion: apps/v1
kind: Deployment
metadata:
  name: summary-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: summary-service
  template:
    metadata:
      labels:
        app: summary-service
    spec:
      containers:
        - name: summary-service
          image: gcr.io/summarizereports/mmv-summary-service:0.0.1-SNAPSHOT
          ports:
            - containerPort: 8100
          resources:
            limits:
              memory: "700Mi"
          env:
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              value: http://naming-server:8761/eureka/
