apiVersion: v1
kind: ConfigMap
metadata:
  name: eureka-config
data:
  EUREKA_SERVER: "http://naming-server:8761/eureka"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: text-to-voice-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: text-to-voice-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: text-to-voice
  template:
    metadata:
      labels:
        app: text-to-voice
    spec:
      containers:
        - name: text-to-voice-container
          image: trexhepaj/text-to-voice:latest
          ports:
            - containerPort: 5000
          env:
            - name: FLASK_APP
              value: "app.py"
            - name: FLASK_ENV
              value: "development"
            - name: EUREKA_SERVER
              valueFrom:
                configMapKeyRef:
                  name: eureka-config
                  key: EUREKA_SERVER
          volumeMounts:
            - mountPath: /app/data
              name: text-to-voice-storage
          resources:
            requests:
              memory: "512Mi"
              cpu: "500m"
            limits:
              memory: "1Gi"
              cpu: "1"
          livenessProbe:
            httpGet:
              path: /healthz
              port: 5000
            initialDelaySeconds: 60
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /readyz
              port: 5000
            initialDelaySeconds: 60
            periodSeconds: 10
      volumes:
        - name: text-to-voice-storage
          persistentVolumeClaim:
            claimName: text-to-voice-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: text-to-voice-service
spec:
  type: LoadBalancer
  ports:
    - port: 5000
      targetPort: 5000
  selector:
    app: text-to-voice
