apiVersion: apps/v1
kind: Deployment
metadata:
  name: usermanagementservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: usermanagementservice
  template:
    metadata:
      labels:
        app: usermanagementservice
    spec:
      containers:
        - name: usermanagementservice
          image: gcr.io/summarizereports/mmv-usermanagementservice:0.0.1-SNAPSHOT
          ports:
            - containerPort: 8300
          resources:
            limits:
              memory: "1500Mi"
          env:
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              value: "http://naming-server:8761/eureka/"
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: "/credentials/summarizereports-f37e9f0f79bb.json"
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:postgresql://postgres-db:5432/users"
            - name: SPRING_DATASOURCE_USERNAME
              value: "postgres"
            - name: SPRING_DATASOURCE_PASSWORD
              value: "1234"
            - name: SPRING_JPA_HIBERNATE_DDL_AUTO
              value: "update"
            - name: SPRING_JPA_PROPERTIES_HIBERNATE_JDBC_LOB_NON_CONTEXTUAL_CREATION
              value: "true"
            - name: SPRING_JPA_PROPERTIES_HIBERNATE_FORMAT_SQL
              value: "true"
          volumeMounts:
            - name: google-credentials-volume
              mountPath: /credentials
              readOnly: true
            - name: app-tmp-volume
              mountPath: /app/tmp
      volumes:
        - name: google-credentials-volume
          secret:
            secretName: google-application-credentials
        - name: app-tmp-volume
          emptyDir: {}
