apiVersion: v1
kind: Service
metadata:
  name: usermanagementservice
spec:
  type: LoadBalancer
  selector:
    app: usermanagementservice
  ports:
    - protocol: TCP
      port: 8300
      targetPort: 8300
