apiVersion: v1
kind: Service
metadata:
  name: user-management-service
spec:
  type: LoadBalancer
  selector:
    app: user-management-service
  ports:
    - protocol: TCP
      port: 8300
      targetPort: 8300
