apiVersion: apps/v1
kind: Deployment
metadata:
  name: usermanagementservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: usermanagementservice
  template:
    metadata:
      labels:
        app: usermanagementservice
    spec:
      containers:
        - name: usermanagementservice
          image: trexhepaj/mmv-usermanagementservice:0.0.1-SNAPSHOT
          securityContext:
            runAsUser: 0
          resources:
            limits:
              memory: "1500Mi"
            requests:
              memory: "1000Mi"
          ports:
            - containerPort: 8300
          env:
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              value: "http://naming-server:8761/eureka/"
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: "/mnt/config/summarizereports-f37e9f0f79bb.json"
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:postgresql://postgres-db:5432/users"
            - name: SPRING_DATASOURCE_USERNAME
              value: "postgres"
            - name: SPRING_DATASOURCE_PASSWORD
              value: "1234"
            - name: SPRING_JPA_HIBERNATE_DDL_AUTO
              value: "update"
            - name: SPRING_JPA_PROPERTIES_HIBERNATE_JDBC_LOB_NON_CONTEXTUAL_CREATION
              value: "true"
            - name: SPRING_JPA_PROPERTIES_HIBERNATE_FORMAT_SQL
              value: "true"
          volumeMounts:
            - mountPath: /mnt/config
              name: config
              subPath: summarizereports-f37e9f0f79bb.json
            - mountPath: /app/tmp
              name: app-tmp
      volumes:
        - name: config
          configMap:
            name: summarizereports-config
        - name: app-tmp
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: usermanagementservice
spec:
  selector:
    app: usermanagementservice
  ports:
    - protocol: TCP
      port: 8300
      targetPort: 8300
  type: ClusterIP
